In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
data_path = "./raw_data"

In [3]:
for dirname, _, filenames in os.walk(data_path):
    for filename in filenames:
        print(os.path.join(dirname, filename))

./raw_data\olist_customers_dataset.csv
./raw_data\olist_geolocation_dataset.csv
./raw_data\olist_orders_dataset.csv
./raw_data\olist_order_items_dataset.csv
./raw_data\olist_order_payments_dataset.csv
./raw_data\olist_order_reviews_dataset.csv
./raw_data\olist_products_dataset.csv
./raw_data\olist_sellers_dataset.csv
./raw_data\product_category_name_translation.csv

In [4]:
files = {
    "customers": "olist_customers_dataset.csv",
    "geolocation": "olist_geolocation_dataset.csv",
    "orders": "olist_orders_dataset.csv",
    "order_items": "olist_order_items_dataset.csv",
    "order_payments": "olist_order_payments_dataset.csv",
    "order_reviews": "olist_order_reviews_dataset.csv",
    "products": "olist_products_dataset.csv",
    "sellers": "olist_sellers_dataset.csv",
    "product_category_name_translation": "product_category_name_translation.csv"
}

In [5]:
files

{'customers': 'olist_customers_dataset.csv',
 'geolocation': 'olist_geolocation_dataset.csv',
 'orders': 'olist_orders_dataset.csv',
 'order_items': 'olist_order_items_dataset.csv',
 'order_payments': 'olist_order_payments_dataset.csv',
 'order_reviews': 'olist_order_reviews_dataset.csv',
 'products': 'olist_products_dataset.csv',
 'sellers': 'olist_sellers_dataset.csv',
 'product_category_name_translation': 'product_category_name_translation.csv'}

In [6]:
dfs = {}
for name, file in files.items():
    file_path = os.path.join(data_path, file)
    dfs[name] = pd.read_csv(file_path)

In [7]:
dfs["orders"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [8]:
for name, df in dfs.items():
    print(f"{name}: {df.shape}")

customers: (99441, 5)
geolocation: (1000163, 5)
orders: (99441, 8)
order_items: (112650, 7)
order_payments: (103886, 5)
order_reviews: (99224, 7)
products: (32951, 9)
sellers: (3095, 4)
product_category_name_translation: (71, 2)

In [9]:
for name, df in dfs.items():
    print(f"\n {name}: {df.columns.tolist()}")

 customers: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

 geolocation: ['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

 orders: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

 order_items: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

 order_payments: ['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

 order_reviews: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

 products: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

 sellers: ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

 product_category_name_translation: ['product_category_name', 'product_category_name_english']

In [10]:
for name, df in dfs.items():
    print(f"\n {name}: {df.dtypes}")

 customers: customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

 geolocation: geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

 orders: order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

 order_items: order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

 order_payments: order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

 order_reviews: review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

 products: product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

 sellers: seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

 product_category_name_translation: product_category_name            object
product_category_name_english    object
dtype: object

In [11]:
for name, df in dfs.items():

    missing_values = df.isnull().sum()
    missing_percentage = df.isnull().mean().multiply(100).sort_values(ascending=False)

    print(f"\n{name}")
    print(f"{missing_values[missing_values > 0]}")
    print(f"{missing_percentage[missing_percentage > 0].round(2)}")

customers
Series([], dtype: int64)
Series([], dtype: float64)

geolocation
Series([], dtype: int64)
Series([], dtype: float64)

orders
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64
order_delivered_customer_date    2.98
order_delivered_carrier_date     1.79
order_approved_at                0.16
dtype: float64

order_items
Series([], dtype: int64)
Series([], dtype: float64)

order_payments
Series([], dtype: int64)
Series([], dtype: float64)

order_reviews
review_comment_title      87656
review_comment_message    58247
dtype: int64
review_comment_title      88.34
review_comment_message    58.70
dtype: float64

products
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
product_category_name         1.85
product_description_lenght    1.85
product_name_lenght           1.85
product_photos_qty            1.85
product_weight_g              0.01
product_height_cm             0.01
product_length_cm             0.01
product_width_cm              0.01
dtype: float64

sellers
Series([], dtype: int64)
Series([], dtype: float64)

product_category_name_translation
Series([], dtype: int64)
Series([], dtype: float64)

In [12]:
for name, df in dfs.items():
    print(name, "duplicates", df.duplicated().sum())

customers duplicates 0

geolocation duplicates 261831
orders duplicates 0
order_items duplicates 0
order_payments duplicates 0
order_reviews duplicates 0
products duplicates 0
sellers duplicates 0
product_category_name_translation duplicates 0

In [13]:
dfs["order_items"].duplicated(subset=["order_id", "order_item_id"]).sum()

np.int64(0)

In [14]:
dfs["customers"]["customer_id"].nunique()
dfs["orders"]["order_id"].nunique()
dfs["products"]["product_id"].nunique()
dfs["sellers"]["seller_id"].nunique()

3095

In [15]:
len(dfs["customers"])

99441

In [16]:
dfs["orders"]["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [17]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

In [18]:
for col in date_columns:
    dfs["orders"][col] = pd.to_datetime(dfs["orders"][col], errors="coerce")

In [19]:
dfs["order_items"]["shipping_limit_date"] = pd.to_datetime(
    dfs["order_items"]["shipping_limit_date"]
)

In [20]:
dfs["orders"].dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [21]:
dfs["order_payments"][["payment_value", "payment_installments"]].describe()

       payment_value  payment_installments
count  103886.000000         103886.000000
mean      154.100380              2.853349
std       217.494064              2.687051
min         0.000000              0.000000
25%        56.790000              1.000000
50%       100.000000              1.000000
75%       171.837500              4.000000
max     13664.080000             24.000000

In [22]:
dfs["products"]["product_category_name"].head()

0               perfumaria
1                    artes
2            esporte_lazer
3                    bebes
4    utilidades_domesticas
Name: product_category_name, dtype: object

In [23]:
dfs["products"]["product_category_name"].str.strip()

0                               perfumaria
1                                    artes
2                            esporte_lazer
3                                    bebes
4                    utilidades_domesticas
                       ...
32946                     moveis_decoracao
32947    construcao_ferramentas_iluminacao
32948                      cama_mesa_banho
32949               informatica_acessorios
32950                      cama_mesa_banho
Name: product_category_name, Length: 32951, dtype: object

In [24]:
dfs["products"]["product_category_name"] = (dfs["products"]["product_category_name"].str.strip())

In [25]:
dfs["products"]["product_category_name"].isna().sum()

np.int64(610)

In [26]:
dfs["products"]["product_category_name"].isna().mean() * 100

np.float64(1.8512336499650999)

In [27]:
missing_category_products = dfs["products"][dfs["products"]["product_category_name"].isna()]["product_id"]
missing_category_products

105      a41e356c76fab66334f36de622ecbd3a
128      d8dee61c2034d6d075997acef1870e9b
145      56139431d72cd51f19eb9f7dae4d1617
154      46b48281eb6d663ced748f324108c733
197      5fb61f482620cb672f5e586bb132eae9
                       ...
32515    b0a0c5dd78e644373b199380612c350a
32589    10dbe0fbaa2c505123c17fdc34a63c56
32616    bd2ada37b58ae94cc838b9c0569fecd8
32772    fa51e914046aab32764c41356b9d4ea4
32852    c4ceee876c82b8328e9c293fa0e1989b
Name: product_id, Length: 610, dtype: object

In [28]:
missing_category_sales = dfs["order_items"][dfs["order_items"]["product_id"].isin(missing_category_products)]["price"].sum()
missing_category_sales

np.float64(179535.28)

In [29]:
missing_category_order_value = dfs["order_items"][dfs["order_items"]["product_id"].isin(missing_category_products)].assign(item_total=lambda x: x["price"] + x["freight_value"])["item_total"].sum()
missing_category_order_value

np.float64(207705.09000000003)

In [30]:
dfs["products"]["product_category_clean"] = (dfs["products"]["product_category_name"].fillna("Unknown"))

In [31]:
product_ids = set(dfs["products"]["product_id"])
unmatched_products = dfs["order_items"][~dfs["order_items"]["product_id"].isin(product_ids)]
print("Unmatched product IDs:", len(unmatched_products))

Unmatched product IDs: 0

In [32]:
print("Missing category:",dfs["products"]["product_category_name"].isna().sum())
print("Missing category %:",dfs["products"]["product_category_name"].isna().mean() * 100)
print("Unmatched product IDs:",(~dfs["order_items"]["product_id"].isin(dfs["products"]["product_id"])).sum())

Missing category: 610
Missing category %: 1.8512336499650999
Unmatched product IDs: 0

In [33]:
dfs["products"]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_clean
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumaria
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,artes
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,esporte_lazer
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,bebes
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,utilidades_domesticas
...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0,moveis_decoracao
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0,construcao_ferramentas_iluminacao
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0,cama_mesa_banho
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,informatica_acessorios
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0,cama_mesa_banho

In [34]:
valid_customers = set(dfs["customers"]["customer_id"])
invalid = ~dfs["orders"]["customer_id"].isin(valid_customers)
invalid.sum()

np.int64(0)

In [35]:
dfs["order_items"][["price", "freight_value"]].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

In [36]:
dfs["order_items"]["item_total"] = (dfs["order_items"]["price"] + dfs["order_items"]["freight_value"])

In [37]:
dfs["order_items"]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,item_total
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,343.40
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,386.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,116.85
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,64.71
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,55.79

In [38]:
print("Total Sales:", dfs["order_items"]['price'].sum())
print("Min Price:", dfs["order_items"]['price'].min())
print("Max Price:", dfs["order_items"]['price'].max())
print("Negative Price:", (dfs["order_items"]['price'] < 0).sum())

Total Sales: 13591643.700000003
Min Price: 0.85
Max Price: 6735.0
Negative Price: 0

In [39]:
print("Total Sales:", dfs["order_items"]['item_total'].sum())
print("Min Price:", dfs["order_items"]['item_total'].min())
print("Max Price:", dfs["order_items"]['item_total'].max())
print("Negative Price:", (dfs["order_items"]['item_total'] < 0).sum())

Total Sales: 15843553.24
Min Price: 6.08
Max Price: 6929.31
Negative Price: 0

In [40]:
dfs["order_items"].dtypes

order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
item_total                    float64
dtype: object

In [41]:
dfs["order_items"].sort_values('price', 
                               ascending=False)[['order_id', 'product_id', 
                               'price', 'freight_value', 'item_total']].head(20)

,order_id,product_id,price,freight_value,item_total
3556,0812eb902a67711a1cb742b3cdaa65ae,489ae2aa008f021502940f251d4cce7f,6735.00,194.31,6929.31
112233,fefacc66af859508bf1a7934eab1e97f,69c590f7ffc7bf8db97190b6cb6ed62e,6729.00,193.21,6922.21
107841,f5136e38d1a14a4dbd87dff67da82701,1bdf5e6731585cf01aa8169c7028d6ad,6499.00,227.66,6726.66
74336,a96610ab360d42a2e5335a3998b4718a,a6492cc69376c469ab6f61d8f44de961,4799.00,151.34,4950.34
11249,199af31afc78c699f0dbf71fb178d4d4,c3ed642d592594bb648ff4a04cee2747,4690.00,74.34,4764.34
62086,8dbc85d1447242f3b127dda390d56e19,259037a6a41845e455183f89c5035f18,4590.00,91.78,4681.78
29193,426a9742b533fc6fed17d1fd6d143d7e,a1beef8f3992dbd4cd8726796aa69c53,4399.87,113.45,4513.32
45843,68101694e5c5dc7330c91e1bbc36214f,6cdf8fc1d741c76586d8b6b15e9eef30,4099.99,75.27,4175.26
78310,b239ca7cd485940b31882363b52e6674,dd113cb02b2af9c8e5787e8f1f0722f6,4059.00,104.51,4163.51
59137,86c4eab1571921a6a6e248ed312f5a5a,6902c1962dd19d540807d0ab8fade5c6,3999.90,17.01,4016.91
56663,80dfedb6d17bf23539beeef3c768f4d7,4ca7b91a31637bd24fb8e559d5e015e4,3999.00,195.76,4194.76
67456,9a3966c23190dbdbaabed08e8429c006,4c50dcc50f1512f46096d6ef0142c4a9,3980.00,62.74,4042.74
28884,41b7766bb1df487d17fb9725b78ff509,0563d4cc419141eab2e5b438046e844e,3930.00,49.55,3979.55
69142,9de73f3e6157169ad6c32b9f313c7dcb,0eb41884a8773e019708fb8409fd8347,3899.00,135.44,4034.44
93516,d3f66901a6743e15f9311547cc623b91,1953c4e517bc25739bc4223ede2ff5bc,3700.00,92.59,3792.59
102349,e85c92ee6a3ba1ef47e41c23286314d9,071930404657f7cd416f75bd063a9d4b,3699.99,36.23,3736.22
72452,a53e05ecd2ed1f46a2b8e1f5828be7c6,dd113cb02b2af9c8e5787e8f1f0722f6,3690.00,136.80,3826.80
98567,df85c824523500d4066a0dbdb5d95bed,5e954c4ed342c50436d25d5f50a34919,3549.00,53.47,3602.47
25648,3a4b013e014723cc38c9faa8ffdc6387,34f99d82cfc355d08d8db780d14aa002,3399.99,126.47,3526.46
107190,f398a143c0fe171d965db2096cf064cf,0c104824e973388d487c67a3d346e96d,3124.00,173.40,3297.40

In [42]:
dfs["orders"]["delivery_days"] = (dfs["orders"]["order_delivered_customer_date"] 
                                  - dfs["orders"]["order_purchase_timestamp"]).dt.days

dfs["orders"]["delivery_delay_days"] = (dfs["orders"]["order_delivered_customer_date"] 
                                        - dfs["orders"]["order_estimated_delivery_date"]).dt.days

dfs["orders"]["delivery_status"] = np.select([dfs["orders"]["order_delivered_customer_date"].isna(), 
                                              dfs["orders"]["delivery_delay_days"] > 0],
                                              ["Not Delivered", "Late"], default="On Time")

In [43]:
dfs["customers"].head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [44]:
dfs["orders"].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_delay_days,delivery_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,-8.0,On Time
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.0,-6.0,On Time
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0,-18.0,On Time
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13.0,-13.0,On Time
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2.0,-10.0,On Time

In [45]:
customers_orders = dfs["orders"].merge(
    dfs["customers"][["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left"
    )
customers_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_delay_days,delivery_status,customer_unique_id
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,-8.0,On Time,7c396fd4830fd04220f754e42b4e5bff
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.0,-6.0,On Time,af07308b275d755c9edb36a90c618231
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0,-18.0,On Time,3a653a41f6f9fc3d2a113cf8398680e8
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13.0,-13.0,On Time,7c142cf63193a1473d2e66489a9ae977
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2.0,-10.0,On Time,72632f0f9dd73dfee390c9b22eb56dd6

In [46]:
customers_orders["customer_unique_id"].isna().sum()

np.int64(0)

In [47]:
customer_orders = (customers_orders.groupby("customer_unique_id")["order_id"].nunique())

In [48]:
customer_type = np.where(customer_orders > 1, "Repeat Customer", "One-time Customer")

In [ ]:
os.makedirs("./cleaned_data", exist_ok=True)

for name, df in dfs.items():
    output_path = f"./cleaned_data/{name}_cleaned.xlsx"
    df.to_excel(output_path, index=False)